Plat 4312 adding vcl functionality
WennerMedia/fastly-promise pull request #2
Opened 2016-12-08 17:18 UTC by billmalarky

This adds service configuration helper methods and VCL helper methods.

2016-12-14 18:36 UTC, chrisboylan approved these changes

2016-12-14 18:38 UTC, mrollinsiv approved these changes

2016-12-14 23:04 UTC, shawnpwalsh requested changes

2016-12-14 23:04 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> +      return (response.headers['content-type'] == 'application/json') ? JSON.parse(response.body) : response.body;
I believe this is an API-breaking change which means it should be 2.0.0 (in package.json)

2016-12-14 23:04 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> +
Are there any VCL-related endpoints that we haven't implemented? If so, should we stub them out so we know what we didn't actually implement?

2016-12-14 23:04 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> +  })
Indentation

2016-12-14 23:04 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> + * @param {boolean} [setVclToMain=false] - Set the uploaded vcl to be the service's "main" vcl.
Document `@return` and `@throws`?

2016-12-14 23:04 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> +  setVclToMain = setVclToMain || false;
Should probably be using ES6 default parameters for `setVclToMain` instead of this line?

2016-12-14 23:04 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> +  return validNamePromise
This chaining is a bit weird. `then` and `catch` above, but more `then`s below?

2016-12-19 19:49 UTC, billmalarky commented on lib/fastlyPromise.js
> +      return (response.headers['content-type'] == 'application/json') ? JSON.parse(response.body) : response.body;
Fair enough.

2016-12-19 20:04 UTC, mrollinsiv commented on package.json
> +  "version": "2.0.0",
I know it's a breaking change but does that warrant a full version change?  Not just 1.1.0?

2016-12-20 21:55 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> +  setVclToMain = setVclToMain || false;
Based on our findings with @mrollinsiv this should not be done.

2016-12-20 21:57 UTC, shawnpwalsh commented on package.json
> +  "version": "2.0.0",
http://semver.org/ describes when to increment MAJOR/MINOR/PATH

2017-01-05 23:23 UTC, shawnpwalsh approved these changes

2017-01-05 23:23 UTC, shawnpwalsh commented on lib/fastlyPromise.js
> +  })
Indentation

2017-01-05 23:36 UTC, merged